name: SSL Certificate Setup

on:
  workflow_dispatch:
    inputs:
      domain:
        description: "Domain name for SSL certificate"
        required: true
        type: string

jobs:
  ssl-setup:
    name: Setup SSL Certificate with Nginx
    runs-on: ubuntu-latest

    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.DROPLET_IP }} >> ~/.ssh/known_hosts

      - name: Install and Configure SSL
        run: |
          ssh ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_IP }} << 'EOF'
          # Update package list
          sudo apt-get update

          # Install Nginx and Certbot
          sudo apt-get install -y nginx certbot python3-certbot-nginx

          # Create basic Nginx configuration for the domain
          sudo tee /etc/nginx/sites-available/${{ github.event.inputs.domain }} << 'NGINX'
          server {
              listen 80;
              server_name ${{ github.event.inputs.domain }};

              location / {
                  proxy_pass http://localhost:3000;
                  proxy_http_version 1.1;
                  proxy_set_header Upgrade $http_upgrade;
                  proxy_set_header Connection 'upgrade';
                  proxy_set_header Host $host;
                  proxy_cache_bypass $http_upgrade;
              }
          }
          NGINX

          # Enable the site
          sudo ln -sf /etc/nginx/sites-available/${{ github.event.inputs.domain }} /etc/nginx/sites-enabled/
          sudo rm -f /etc/nginx/sites-enabled/default

          # Test Nginx configuration
          sudo nginx -t

          # Start/Restart Nginx
          sudo systemctl restart nginx

          # Obtain SSL certificate
          sudo certbot --nginx \
            --non-interactive \
            --agree-tos \
            --email ${{ secrets.SSL_EMAIL }} \
            -d ${{ github.event.inputs.domain }}

          # Setup automatic renewal
          sudo systemctl enable certbot.timer
          sudo systemctl start certbot.timer

          # Test renewal process
          sudo certbot renew --dry-run

          # Verify Nginx status
          sudo systemctl status nginx

          # Show certificate information
          sudo certbot certificates
          EOF

      - name: Verify Setup
        run: |
          echo "SSL certificate setup completed for ${{ github.event.inputs.domain }}"
